# Generated by Django 3.1.6 on 2021-02-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20210219_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='login',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
