# Generated by Django 3.1.6 on 2021-02-20 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_assignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
